name = "VT100"
uuid = "7774df62-37c0-5c21-b34d-f6d7f98f54bc"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
ColorTypes = "0.7 - 0.11"
FixedPointNumbers = "0.5 - 0.8"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
